---
- name: Install InfluxData packages repository key
  apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray 
    state: present

- name: Declare Grafana package repository
  apt_repository:
    repo: deb https://dl.bintray.com/fg2it/deb jessie main
    state: present

- name: Install Grafana package and dependencies
  apt: 
    update_cache: yes
    state: latest
    name:  "{{item}}"
  with_items: 
    - apt-transport-https
    - grafana

- name: Declare and run Grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started
    