# [domoticz]
# raspi000.local ansible_user=pi 

# [cluster01]
# raspi001.local ansible_user=pi 
# raspi002.local ansible_user=pi 
# raspi003.local ansible_user=pi 
# raspi004.local ansible_user=pi 
# raspi005.local ansible_user=pi 

# [others]
# volumio.local ansible_user=volumio

# [all:children]
# domoticz
# cluster01
# others


all:
  children:
    domoticz:
      hosts: 
        raspi000.local:
      vars:
        ansible_user: pi
    cluster01: 
      hosts:
        raspi001.local:
        raspi002.local:
        raspi003.local:
        raspi004.local:
        raspi005.local:
      vars:
        ansible_user: pi
    others:
      hosts:
        volumio.local:
      vars:
        ansible_user: volumio
