all:
  children:
    domoticz:
      hosts: 
        raspi000.local:
      vars:
        ansible_user: pi
    cluster01: 
      hosts:
        raspi001.local:
        raspi002.local:
        raspi003.local:
      vars:
        ansible_user: pi
    cluster02: 
      hosts:
        raspi004.local:
        raspi005.local:
      vars:
        ansible_user: ubuntu
