---
- name: Configure a cluster of Raspberry's for IoT usage.
  hosts: all
  become: true

  roles:
    - standard
    
- hosts: raspi000.local
  become: true
  roles:
    - nginx
    - telegraf

- hosts: raspi001.local
  become: true
  roles:
    - rabbitmq
    - telegraf

- hosts: raspi002.local
  become: true
  roles:
#    - nodered
    - telegraf

- hosts: raspi003.local
  become: true
  roles:
    - nfs_client
    - influxdb
#    - grafana
    - telegraf
