---
- name: Configure a cluster of Raspberry's for IoT usage.
  hosts: all
  become: true

  roles:
    - standard
    
- hosts: raspi000.local
  become: true
  roles:
    - nginx

- hosts: raspi001.local
  become: true
  roles:
    - rabbitmq

- hosts: raspi002.local
  become: true
  roles:
    - nodered

- hosts: raspi003.local
  become: true
  roles:
    - influxdb
