---
- name: Configure a cluster of Raspberries.
  hosts: all
  become: true
  roles:
    - standard
    - telegraf
    - geerlingguy.nfs
    - docker
    - kubernetes
    
- hosts: raspi000.local
  become: true
  roles:
    - nginx
    - SimpliField.node

- hosts: raspi001.local
  become: true
  roles:
    - rabbitmq

- hosts: raspi002.local
  become: true
  roles:
#    - nodered

- hosts: raspi003.local
  become: true
  roles:
    - influxdb
    - grafana
