---
- name: Configure a cluster of Raspberries.
  hosts: all
  become: true
  roles:
    - standard
    - nfs_client
    - docker
    
- hosts: raspi000.local
  become: true
  roles:
    - SimpliField.node

- hosts: raspi001.local
  become: true
  roles:
    - rabbitmq

- hosts: raspi002.local
  become: true
  roles:
#    - nodered

- hosts: raspi003.local
  become: true
  roles:
    - influxdb
    - grafana
