---
- name: Install node source packages repository key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Declare nodesource package repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_7.x jessie main
    state: present

- name: Install NodeJS package
  apt: 
    update_cache: yes
    state: latest
    name: nodejs

