---
- name: Install basic raspberry server packages
  apt: 
    update_cache=yes
    state=latest
    name={{item}}
  with_items: 
    - curl
    - htop
    - ncdu
    - tar
    - unzip
    - vim
    - wget
    - locate
    - mc
    - nmap
    - apt-transport-https
    - ca-certificates
    - ntp

- name: Install public ssh keys
  authorized_key:
    user: pi
    state: present
    key: '{{ item }}'
  with_file:
    - files/public_keys/id_rsa.pub

