---
- name: Install basic raspberry server packages
  apt: 
    update_cache=yes
    state=latest
    name={{item}}
  with_items: 
    - curl
    - htop
    - ncdu
    - tar
    - unzip
    - vim
    - wget
    - locate
    - mc
    - nmap
    - apt-transport-https
    - ca-certificates
    - ntp

- name: Install public ssh keys
  authorized_key:
    user: '{{ ansible_user }}'
    state: present
    key: '{{ item }}'
  with_file:
    - files/public_keys/id_rsa.pub

- name: Install bash related files for default user
  template:
    src: '{{item}}.j2'
    dest: '/home/{{ ansible_user }}/.{{item}}'
  with_items:
    - bashrc
    - bash_aliases
    - bash_profile
  tags:
    - bash