- name: Install nfs-client package and dependencies
  apt: 
    update_cache: yes
    state: latest
    name:  "{{item}}"
  with_items: 
    - nfs-client

- name: Make sure that rpcbind is running
  service:
    name: rpcbind
    enabled: yes
    state: started 

- name: Create mountable directory
  file:
    path: /mnt/shared
    state: directory
    mode: '0777'
    owner: root
    group: root

- name: Mount common volume
  mount:
    path: /mnt/shared 
    src: warka.local:/volume1/shared
    fstype: nfs
    opts: defaults
    state: mounted
